version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Porta AMQP para comunicação
      - "15672:15672"  # Painel de administração
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - springboot-mq-net

  app:
    image: exerc3-itau-unibanco-image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exerc3-itau-unibanco
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
    ports:
      - "8080:8080"  # Porta da aplicação Spring Boot
    networks:
      - springboot-mq-net

networks:
  springboot-mq-net: